### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by ddelpero** [romshark/templier#8]
Is it possible to define environment variables in the yml file? 

I can include them in the command line, for example:

OBENV=DEVELOPMENT OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318 templier --config ./templier.yml

But it would be nice to able to set those in the yml file.

**Comment by romshark** [comment]
I might want to add `env` to https://github.com/romshark/templier/blob/86d16df680a9c80f383ff6b9d1772cbc5ef057cb/internal/config/config.go#L69

**Comment by ddelpero** [comment]
To avoid adding each env to ConfigApp, I added
  
  `Env map[string]string `yaml:"env"``

map[string]string isn't ideal, and if I have a string that represents a URL, http://localhost:4318, gets converted to http:////localhost:4318.

I can change Env to something like Environment, and then the string URL remains. 

Do you have any suggestions?
